version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8100:8200"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: